version: '3.8'

services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8100:8100"

    depends_on:
      - discovery-service
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8200:8200"

    depends_on:
      - discovery-service
      - product-service

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8765:8765"
      
    depends_on:
      - discovery-service
      - product-service
      - order-service